server:
  port: 9003

spring.datasource:
  url: jdbc:mysql://localhost/topneeds
  username: root
  password: Aurorau2425@
  driverClassName: com.mysql.jdbc.Driver
  testWhileIdle: true
  validationQuery: SELECT 1
  timeBetweenEvictionRunsMillis: 60000