server:
  port: 9003

---
spring:
  profiles: dev

#spring.datasource:
#  url: jdbc:mysql://localhost:3306/topneeds
#  username: root
#  password: Aurorau2425@
#  driverClassName: com.mysql.jdbc.Driver
#  testWhileIdle: true
#  validationQuery: SELECT 1
#  timeBetweenEvictionRunsMillis: 60000